/**
 * Generated by [@platform/cell.http] for CellOS namespace:
 *
 *      ns:foo
 *
 * Notes:
 *
 *    - Do NOT manually edit this file.
 *    - Do check this file into source control.
 *    - Import the [.d.ts] file within your consuming module
 *      that uses [TypedSheet]'s to operate on the namespace
 *      programatically with strong-typing.
 *
 */

export declare type MyRow = {
  title: string;
  isEnabled: boolean;
  color: MyColor;
};

export declare type MyColor = {
  label: string;
  color: 'red' | 'green' | 'blue';
};
