/**
 * Generated by [@platform/cell.http] for CellOS namespace:
 * 
 *      ns:foo
 * 
 * Notes: 
 *    - Do NOT manually edit this file.
 *    - Do check this file into source control.
 *    - Import the [.d.ts] file within the consuming module
 *      that uses [TypedSheet]'s to operate on the namespace
 *      programatically with strong-typing.
 */

export declare type MySheet = {
  title: string;
  isEnabled: boolean;
  colors: ColorSetting;
};

export declare type ColorSetting = {
  label: string;
  color: "red" | "green" | "blue";
};
