import { fs, cheerio, t } from '../common';

/**
 * Extracts a manifest of paths from the given input HTML file
 * generated by ParcelJS.
 */
export async function fromFile(entry: string): Promise<t.IBundleEntryFileManifest> {
  const file = fs.resolve(entry);
  const exists = await fs.pathExists(file);
  if (!exists) {
    return { entry, exists, scripts: [], stylesheets: [] };
  } else {
    const html = (await fs.readFile(file)).toString();
    return { ...fromHtml(html), entry, exists };
  }
}

/**
 * Extracts a manifest of paths from the given input HTML
 * generated by ParcelJS.
 */
export function fromHtml(html: string): t.IBundleEntryManifest {
  const $ = cheerio.load(html);
  return {
    scripts: getAttributes($('script'), 'src'),
    stylesheets: getAttributes($('link[rel="stylesheet"]'), 'href'),
  };
}

/**
 * [Helpers]
 */
function getAttributes(input: Cheerio, attr: string) {
  const attributes: string[] = [];
  input.each((i, el) => {
    const value = el.attribs[attr];
    if (value) {
      attributes.push(value);
    }
  });
  return attributes;
}
