import { constants, t, value } from '../common';
import { TypeScript } from '../TypeScript';

/**
 * Converts type definitions to valid typescript declarations.
 */

export function typescript(def: t.INsTypeDef, options: { header?: boolean } = {}) {
  const api = {
    /**
     * Comments to insert at the head of the typescript.
     */
    get header() {
      const uri = def.uri;
      const pkg = constants.PKG.name || 'Unnamed';
      return toTypescriptHeader({ uri, pkg });
    },

    /**
     * Generated typescript decalration(s).
     */
    get declaration() {
      const header = value.defaultValue(options.header, true) ? api.header : undefined;
      const typename = def.typename;
      const types = def.columns.map(({ prop, type, optional }) => ({ prop, type, optional }));
      return TypeScript.toDeclaration({ typename, types, header });
    },

    /**
     * Save the typescript declarations as a binary file.
     */
    async save(fs: t.IFs, dir: string, options: { filename?: string } = {}) {
      // Prepare paths.
      await fs.ensureDir(dir);
      let path = fs.join(dir, options.filename || def.typename);
      path = path.endsWith('.d.ts') ? path : `${path}.d.ts`;

      // Save file.
      const data = api.declaration;
      await fs.writeFile(path, data);
      return { path, data };
    },

    toString() {
      return api.declaration;
    },
  };

  return api;
}

/**
 * [Helpers]
 */

function toTypescriptHeader(args: { uri: string; pkg: string }) {
  return `
  /**
   * Generated by [${args.pkg}] for namespace:
   * 
   *      "${args.uri}"
   * 
   * Notes: 
   * 
   *    - Do NOT manually edit this file.
   *    - Do check this file into source control.
   *    - Import the [.d.ts] file within your consuming module
   *      that uses [TypedSheet]'s to operate on the namespace
   *      programatically with strong-typing.
   * 
   */`.substring(1);
}
